/**
 * Copyright (c) HashiCorp, Inc.
 * SPDX-License-Identifier: MPL-2.0
 */

// generated by cdktf get
Object.defineProperty(exports, 'database', { get: function () { return require('./database'); } });
Object.defineProperty(exports, 'defaultPrivileges', { get: function () { return require('./default-privileges'); } });
Object.defineProperty(exports, 'extension', { get: function () { return require('./extension'); } });
Object.defineProperty(exports, 'functionResource', { get: function () { return require('./function-resource'); } });
Object.defineProperty(exports, 'grant', { get: function () { return require('./grant'); } });
Object.defineProperty(exports, 'grantRole', { get: function () { return require('./grant-role'); } });
Object.defineProperty(exports, 'physicalReplicationSlot', { get: function () { return require('./physical-replication-slot'); } });
Object.defineProperty(exports, 'publication', { get: function () { return require('./publication'); } });
Object.defineProperty(exports, 'replicationSlot', { get: function () { return require('./replication-slot'); } });
Object.defineProperty(exports, 'role', { get: function () { return require('./role'); } });
Object.defineProperty(exports, 'schema', { get: function () { return require('./schema'); } });
Object.defineProperty(exports, 'server', { get: function () { return require('./server'); } });
Object.defineProperty(exports, 'subscription', { get: function () { return require('./subscription'); } });
Object.defineProperty(exports, 'userMapping', { get: function () { return require('./user-mapping'); } });
Object.defineProperty(exports, 'dataPostgresqlSchemas', { get: function () { return require('./data-postgresql-schemas'); } });
Object.defineProperty(exports, 'dataPostgresqlSequences', { get: function () { return require('./data-postgresql-sequences'); } });
Object.defineProperty(exports, 'dataPostgresqlTables', { get: function () { return require('./data-postgresql-tables'); } });
Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });

